# Generated by Django 2.2.3 on 2019-07-13 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefecture', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Alldata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data1', models.FloatField()),
                ('data2', models.FloatField()),
                ('hensa', models.FloatField()),
                ('cate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Category')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Prefecture')),
                ('static_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Deviation')),
            ],
        ),
    ]
